image: mono:4.4.0.182

stages:
  - build
  - test

build:
  stage: build
  script:
    - nuget restore ./GServer/
    - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" ./GServer/GServer.sln
  
test:
  stage: test
  script:
    - ls
    #- mono ./GServer/packages/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./GServer/Unit-Tests/bin/Release/Unit-Tests.dll /noresult

cache:
  paths:
    - /
